version: '3.3'

services:
  mongodb:
    image: "bitnami/mongodb:4.4"
    ports:
      - "27017:27017"
    environment:
      MONGODB_ADVERTISED_HOSTNAME: "localhost"
      MONGODB_REPLICA_SET_MODE: "primary"
      MONGODB_REPLICA_SET_NAME: "replicaset"
      MONGODB_REPLICA_SET_KEY: "replicasetkey"
      MONGODB_ROOT_PASSWORD: "password"